gp3_labels = c(
  subj_id = "FXS ID",
  redcap_event_name = "Event Name",
  visit_age = "Age at visit",
  mds_med_ca_other="Other Cancer (detailed)",
  new_mds_med_can_other="Other Cancer",

  new_mds_med_anes1="Anesthesia (new_mds_med_anes1)",
  medic_surg_anes="Anesthesia (medic_surg_anes)",
  pp_t1rlb_total ="Purdue pegboard 1st Trial Total, R+L+B",
  mds_med_thy ="Thyroid problems",
  # new_mds_med_thy ="Thyroid problems",
  mds_med_hyothy ="Hypothyroid",
  # new_mds_med_hyothy ="Hypothyroid",
  mds_med_hyethy ="Hyperthyroid",
  # new_mds_med_hyethy ="Hyperthyroid",

  sex = "Gender",
  mol_apoe = "ApoE",
  mol_dna_result = "Floras Non-Sortable Allele Size (CGG) Results",
  mds_psy_drug = "Drug use",
  mds_psy_drug_notes = "Drugs used",
  new_mds_psy_drug_marij = "Marijuana use",
  mds_psy_alco = "Alcohol use/abuse",
  mds_psy_dri = "# of drinks per day now",
  mds_med_thyca = "Thyroid Cancer",
  new_mds_med_skin = "Skin Cancer",
  new_mds_med_mela = "Melanoma",
  mds_med_proca = "Prostate Cancer",
  mds_med_sur = "Surgery",
  mds_med_sur_notes = "Surgery type",
  new_mds_med_sur1 = "Surgery: Type/Age",
  new_mds_med_sur2 = "Surgery 2: Type/Age",
  new_mds_med_sur3 = "Surgery 3: Type/Age",
  mds_ne_it = "Intention tremor",
  mds_ne_rt = "Resting tremor",
  mds_ne_pt = "Postural tremor",
  mds_neu_trem_irm = "Intermittent tremor",
  mds_neu_trem_age = "Tremor: Age of onset",
  new_mds_neu_trem_head = "Head tremor",
  new_mds_neu_trem_age2 = "Head Tremor: Age of onset",
  mds_neu_atax = "Ataxia",
  mds_neu_atax_age = "Ataxia: Age of onset",
  mds_neu_atax_sev = "Ataxia: severity",
  # new_mds_ne_ga = "Ataxia",
  new_mds_med_park = "Parkinsons",
  mds_ne_pf = "Parkinsonian features",
  mds_ne_pfmf = "Parkinsonian features: Masked faces",
  mds_ne_pfit = "Parkinsonian features: Increased tone",
  mds_ne_pfprt = "Parkinsonian features: Pill rolling tremor",
  mds_ne_pfsg = "Parkinsonian features: Stiff gait",
  mds_fxtas_stage = "FXTAS Stage (0-5)",
  bds2_score = "BDS-2 Total Score",
  mmse_totalscore = "MMSE Total Score",
  scid_dxcode1 = "Interviewers Diagnosis 1,  by Code",
  scid_dx1age = "Interviewers Diagnosis 1, Age of Onset",
  scid_dxcode2 = "Interviewers Diagnosis 2,  by Code",
  scid_dx2age = "Interviewers Diagnosis 2, Age of Onset",
  scid_dxcode3 = "Interviewers Diagnosis 3,  by Code",
  scid_dx3age = "Interviewers Diagnosis 3, Age of Onset",
  scl_s_som_ts = "SCL90: Somatization",
  scl_s_oc_ts = "SCL90: Obsessive-Compulsive",
  scl_s_is_ts = "SCL90: Interpersonal Sensitivity",
  scl_s_dep_ts = "SCL90: Depression",
  scl_s_anx_ts = "SCL90: Anxiety",
  scl_s_hos_ts = "SCL90: Hostility",
  scl_s_phob_ts = "SCL90: Phobia",
  scl_s_par_ts = "SCL90: Paranoid Ideation",
  scl_s_psy_ts = "SCL90: Psychoticism",
  scl_s_gsi_ts = "SCL90: Global Severity Index",
  scl_s_psdi_ts = "SCL90: Positive Symptom Distress Index",
  scl_s_pst_ts = "SCL90: Positive Symptom Total",

  # update verbal and full scale IQ names to combine with gp4

  # wais_verb_iq = "Verbal: IQ Score",
  # update to WAIS 4 name: "Verbal Comprehension: Composite Score (VCI)"
  wais_verb_iq = "Verbal Comprehension: Composite Score (VCI)",
  wais_perf_iq = "Performance: IQ Score",
  # wais_fullscale_iq = "Full Scale: IQ Score",
  # update to WAIS 4 name:
  wais_fullscale_iq = "Full Scale: Composite Score (FSIQ)",

  cantab_ots_probsolvedfirstchoice_ = "OTS Problems solved on first choice",
  cantab_pal_toterrors_adjusted = "PAL Total errors (adjusted)",
  cantab_sst_medianrt_gotrials = "SST Median correct RT on GO trials",
  cantab_rvp_a = "RVP A signal detection",
  cantab_rti_5choice_movement = "RTI Five-choice movement time",
  cantab_swm_between_errors = "SWM Between errors",

  mds_med_lup = "Lupus",
  mds_med_ra = "Rheumatoid arthritis",
  mds_med_mswk = "Multiple Sclerosis: Workup",
  new_mds_med_ana = "ANA positive",
  mds_med_sjo = "Sjogrens Syndrome",
  mds_med_ray = "Raynauds Syndrome",
  new_mds_med_pulm = "Pulmonary Fibrosis",
  mds_med_ido_notes = "Other immunological disease & other symptoms: list",

  mri_cere_atr = "Cerebral Atrophy",
  mri_cerebel_atr = "Cerebellar Atrophy",
  mri_cere_wm_hyper = "Cerebral WM Hyperintensity", mri_cerebel_wm_hyper = "Cerebellar WM Hyperintensity",
  mri_mcp_wm_hyper = "MCP-WM Hyperintensity", mri_pons_wm_hyper = "Pons-WM Hyperintensity",
  mri_subins_wm_hyper = "Sub-Insular WM Hyperintensity", mri_peri_wm_hyper = "Periventricular WM Hyperintensity",
  mri_splen_wm_hyper = "Splenium (CC)-WM Hyperintensity", mri_genu_wm_hyper = "Genu (CC)-WM Hyperintensity",
  mri_corp_call_thick = "Corpus Callosum-Thickness", ds_crx1 = "Current Medications 1",
  ds_crx2 = "Current Medications 2", ds_crx3 = "Current Medications 3",
  ds_crx4 = "Current Medications 4", ds_crx5 = "Current Medications 5",
  ds_crx6 = "Current Medications 6", ds_crx7 = "Current Medications 7",
  ds_crx8 = "Current Medications 8", ds_crx9 = "Current Medications 9",
  ds_crx10 = "Current Medications 10",
  dem_race="Primary Race",
  dem_eth="Primary Ethnicity",
  dem_date="Visit Date",

  mds_med_thy = "Thyroid problems",
  # new_mds_med_thy = "Thyroid problems",
  mds_med_hyothy = "Hypothyroid",
  # new_mds_med_hyothy = "Hypothyroid",
  mds_med_hyethy = "Hyperthyroid",
  # new_mds_med_hyethy = "Hyperthyroid",
  scid_admin = "Was SCID completed?",
  scid_reason = "If No, please comment:",
  scid_md01lif = "Bipolar I Disorder (MD01), Lifetime",
  scid_md01cur = "Bipolar I Disorder (MD01), Current",
  scid_md02lif = "Bipolar II Disorder (MD02), Lifetime",
  scid_md02cur = "Bipolar II Disorder (MD02), Current",
  scid_md03cur = "Other Bipolar Disorder (MD03), Current",
  scid_md03lif = "Other Bipolar Disorder (MD03), Lifetime",
  scid_md04cur = "Major Depressive Disorder (MD04), Current",
  scid_md04lif = "Major Depressive Disorder (MD04), Lifetime",
  scid_md07cur = "Mood Disorder Due to a GMC (MD07), Current",
  scid_md07lif = "Mood Disorder Due to GMC (MD07), Lifetime",
  scid_md08cur = "Substance-Induced Mood Dis. (MD08), Current",
  scid_md08lif = "Substance-Induced Mood Dis. (MD08), Lifetime",
  scid_ps01cur = "Primary Psychotic Symptoms (PS01), Current",
  scid_ps01lif = "Primary Psychotic Symptoms (PS01), Lifetime")

gp4_labels = c(
  subj_id = "FXS ID",
  redcap_event_name = "Event Name",
  new_mds_med_anes1="Anesthesia (new_mds_med_anes1)",
  medic_surg_anes="Anesthesia (medic_surg_anes)",
  pp_t1rlb_total ="Purdue pegboard 1st Trial Total, R+L+B",
  new_mds_med_can_notes ="Cancer Notes",
  new_mds_med_thy ="Thyroid problems",
  new_mds_med_hyothy ="Hypothyroid",
  new_mds_med_hyethy ="Hyperthyroid",
  scid_admin ="Was SCID completed?",
  scid_reason ="If No, please comment:",
  scid_md01lif ="Bipolar I Disorder (MD01), Lifetime",
  scid_md01cur ="Bipolar I Disorder (MD01), Current",
  scid_md02lif ="Bipolar II Disorder (MD02), Lifetime",
  scid_md02cur ="Bipolar II Disorder (MD02), Current",
  scid_md03cur ="Other Bipolar Disorder (MD03), Current",
  scid_md03lif ="Other Bipolar Disorder (MD03), Lifetime",
  scid_md04lif ="Major Depressive Disorder (MD04), Lifetime",
  scid_md04cur ="Major Depressive Disorder (MD04), Current",
  scid_md07lif ="Mood Disorder Due to GMC (MD07), Lifetime",
  scid_md07cur ="Mood Disorder Due to a GMC (MD07), Current",
  scid_md08lif ="Substance-Induced Mood Dis. (MD08), Lifetime",
  scid_md08cur ="Substance-Induced Mood Dis. (MD08), Current",
  scid_ps01lif ="Primary Psychotic Symptoms (PS01), Lifetime",
  scid_ps01cur ="Primary Psychotic Symptoms (PS01), Current",
  sex = "Gender",
  visit_age = "Age at visit",
  mol_apoe = "ApoE",
  mol_dna_result = "Floras Non-Sortable Allele Size (CGG) Results",
  new_mds_psy_drug = "Drug use",
  new_mds_psy_drug_notes = "Drugs used",
  new_mds_psy_drug_marij = "Marijuana use",
  new_mds_psy_alco = "Alcohol use/abuse",
  new_mds_psy_dri = "# of drinks per day now", #range= 0-20; -2= < 1/day; 999= no response
  new_mds_med_thyca = "Thyroid Cancer",
  new_mds_med_skin = "Skin Cancer",
  new_mds_med_mela = "Melanoma",
  new_mds_med_proca = "Prostate Cancer",
  new_mds_med_can_other="Other Cancer",
  new_mds_med_sur1 = "Surgery: Type/Age",
  new_mds_med_sur2 = "Surgery 2: Type/Age",
  new_mds_med_sur3 = "Surgery 3: Type/Age",
  new_mds_med_sur4 = "Surgery 4: Type/Age",
  new_mds_med_sur5 = "Surgery 5: Type/Age",
  new_mds_neu_trem_int = "Intention tremor",
  new_mds_neu_trem_rest = "Resting tremor",
  new_mds_neu_trem_pos = "Postural tremor",
  new_mds_neu_trem_irm = "Intermittent tremor",
  new_mds_neu_trem_age = "Tremor: Age of onset",
  new_mds_neu_trem_head = "Head tremor",
  new_mds_neu_trem_age2 = "Head Tremor: Age of onset",
  new_mds_neu_atax = "Walking/ataxia Problems",
  new_mds_neu_atax_age = "Ataxia: Age of onset",
  new_mds_ne_ga = "Ataxia",
  new_mds_ne_gas = "Ataxia: severity",
  new_mds_med_park = "Parkinsons",
  new_mds_ne_pf = "Parkinsonian features",
  new_mds_ne_pfmf = "Parkinsonian features: Masked faces",
  new_mds_ne_pfit = "Parkinsonian features: Increased tone",
  new_mds_ne_pfprt = "Parkinsonian features: Pill rolling tremor",
  new_mds_ne_pfsg = "Parkinsonian features: Stiff gait",
  new_mds_fxtas_stage = "FXTAS Stage (0-5)",
  bds2_score = "BDS-2 Total Score",
  mmse_totalscore = "MMSE Total Score",
  scid_dxcode1 = "Interviewers Diagnosis 1,  by Code",
  scid_dx1age = "Interviewers Diagnosis 1, Age of Onset",
  scid_dxcode2 = "Interviewers Diagnosis 2,  by Code",
  scid_dx2age = "Interviewers Diagnosis 2, Age of Onset",
  scid_dxcode3 = "Interviewers Diagnosis 3,  by Code",
  scid_dx3age = "Interviewers Diagnosis 3, Age of Onset",
  scl_s_som_ts = "SCL90: Somatization",
  scl_s_oc_ts = "SCL90: Obsessive-Compulsive",
  scl_s_is_ts = "SCL90: Interpersonal Sensitivity",
  scl_s_dep_ts = "SCL90: Depression",
  scl_s_anx_ts = "SCL90: Anxiety",
  scl_s_hos_ts = "SCL90: Hostility",
  scl_s_phob_ts = "SCL90: Phobia",
  scl_s_par_ts = "SCL90: Paranoid Ideation",
  scl_s_psy_ts = "SCL90: Psychoticism",
  scl_s_gsi_ts = "SCL90: Global Severity Index",
  scl_s_psdi_ts = "SCL90: Positive Symptom Distress Index",
  scl_s_pst_ts = "SCL90: Positive Symptom Total",

  wais4_verbcomp_cs  = "Verbal Comprehension: Composite Score (VCI)",
  wais4_percorg_cs   = "Perceptual Reasoning: Composite Score (PRI)",
  wais4_workmem_cs   = "Working Memory: Composite Score (WMI)",
  wais4_procspeed_cs = "Processing Speed: Composite Score (PSI)",
  wais4_fullscale_cs = "Full Scale: Composite Score (FSIQ)",

  # old cantab vars
  # cantab_ots_probsolvedfirstchoice_ = "OTS Problems solved on first choice",
  # cantab_pal_toterrors_adjusted = "PAL Total errors (adjusted)",
  # cantab_sst_medianrt_gotrials = "SST Median correct RT on GO trials",
  # cantab_rvp_a = "RVP A signal detection",
  # cantab_rti_5choice_movement = "RTI Five-choice movement time",
  # cantab_swm_between_errors = "SWM Between errors",

  new_mds_med_lup = "Lupus",
  new_mds_med_ra = "Rheumatoid arthritis",
  new_mds_med_mswk = "Multiple Sclerosis: Workup",
  new_mds_med_ana = "ANA positive",
  new_mds_med_sjo = "Sjogrens Syndrome",
  new_mds_med_ray = "Raynauds Syndrome",
  new_mds_med_pulm = "Pulmonary Fibrosis",
  new_mds_med_immun_notes = "Immunological Notes",

  mri_cere_atr = "Cerebral Atrophy",
  mri_cerebel_atr = "Cerebellar Atrophy",
  mri_cere_wm_hyper = "Cerebral WM Hyperintensity",
  mri_cerebel_wm_hyper = "Cerebellar WM Hyperintensity",
  mri_mcp_wm_hyper = "MCP-WM Hyperintensity",
  mri_pons_wm_hyper = "Pons-WM Hyperintensity",
  mri_subins_wm_hyper = "Sub-Insular WM Hyperintensity",
  mri_peri_wm_hyper = "Periventricular WM Hyperintensity",
  mri_splen_wm_hyper = "Splenium (CC)-WM Hyperintensity",
  mri_genu_wm_hyper = "Genu (CC)-WM Hyperintensity",
  mri_corp_call_thick = "Corpus Callosum-Thickness",
  new_ds_crx1 = "Current Medications 1", new_ds_crx2 = "Current Medications 2",
  new_ds_crx3 = "Current Medications 3", new_ds_crx4 = "Current Medications 4",
  new_ds_crx5 = "Current Medications 5", new_ds_crx6 = "Current Medications 6",
  new_ds_crx7 = "Current Medications 7", new_ds_crx8 = "Current Medications 8",
  new_ds_crx9 = "Current Medications 9", new_ds_crx10 = "Current Medications 10",
  dem_date = "Visit Date",
  dem_race ="Primary Race",
  dem_eth ="Primary Ethnicity",

  # cantab_conn
  otspsfc = "OTS Problems solved on first choice",
  paltea28 = "PAL Total errors (adjusted)",
  sstmrtg = "SST Median correct RT on GO trials",
  rvpa = "RVP A signal detection",
  rtifmdmt = "RTI Five-choice movement time",
  swmbe468 = "SWM Between errors",
  kin_l_resttrem="Kinesia Left Rest Tremor",
  kin_l_posttrem="Kinesia Left Postural Tremor",
  kin_l_kintrem ="Kinesia Left Kinetic Tremor",
  kin_r_resttrem="Kinesia Right Rest Tremor",
  kin_r_posttrem="Kinesia Right Postural Tremor",
  kin_r_kintrem ="Kinesia Right Kinetic Tremor",
  moca_tot_score ="MOCA Total score"
)

all_labels = c(gp4_labels, gp3_labels)
labels_table = tibble(
  label = all_labels,
  varname = names(all_labels),

  ) |>
  distinct() |>
  arrange(label, varname)

readr::write_csv(labels_table, "output/var_list.csv")
# usethis::use_data(vars_and_labels, overwrite = TRUE)
