---
title: "Questions about FXTAS Sequence Data"
format:
  html:
    toc: true
    toc-depth: 4
    toc-float: true
    number-sections: true
    embed-resources: true
  docx:
    number-sections: true
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 4
)

# update 'asis' chunk to allow inline code
knitr::knit_engines$set(asis = function(options) {
  if (options$echo && options$eval) knitr::knit_child(text = options$code)
})
```

```{r setup}
#| message: false
library(fxtas)
devtools::load_all()
library(pander)
library(table1)
library(dplyr)
library(magrittr)
NA.label1 = "Missing"
column_var = "Recruited in study phase"
column_var = "FX**"
# load_all()

phase <- ifelse(column_var == "Recruited in study phase", TRUE, FALSE)
cgg <- ifelse(column_var == "FX**", TRUE, FALSE)
```

# General data processing notes

## Missing codes

The missing codes 777, 888, and 999 were converted to `NA` for all variables, unless noted otherwise below.

# Data from first visits

## FXTAS Stage

```{r}

vars = c(
  "FXTAS Stage (0-5)",
  "FXTAS Stage (0-5)*")
```

<br>

List of patients with missing FXTAS Stage:  

:::{.callout-note}
<b>The list can be downloaded to `csv` or `excel` by clicking on the `Download` button at the top of the table.</b>
:::

```{r}
fxtas_stage_na <- visit1 |>
  dplyr::filter(is.na(`FXTAS Stage (0-5)`)) |>
  dplyr::select(`FXS ID`, `Event Name`, `FXTAS Stage (0-5)`)
  
```

```{r}
display_DT(fxtas_stage_na, "GP3_GP4_FXTAS_Stage", group = FALSE)
```
