---
title: "exploration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exploration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 4
)
```

```{r setup}
library(fxtas)
# load_all()
```

## plotly

```{r}

library(plotly)
library(dplyr)
gp34 |> 
  nest_by(Study) |> 
  mutate(
    p = 
      plot_ly(data,
              type = "scatter",
              mode = "lines+markers",
              color = ~`FXS ID`,
              x = ~`Event Name`,
              y = ~`Age at visit`,
              showlegend = FALSE
      ) |> 
      plotly::layout(
        xaxis = list(title = "")
        # title = "banana"
      ) |> 
      list()
  ) |> 
  pull(p) |> 
  plotly::subplot(
    nrows = 1, shareX = TRUE, shareY = TRUE)

```

## ggplot

```{r}

library(ggplot2)

plot1 = gp34 |> 
  ggplot(
    data = _,
    mapping = aes(
      color = `FXS ID`,
      group = `FXS ID`,
      y = `Event Name`,
      x = `Age at visit`
    )) +
  geom_point() + 
  geom_line() +
  theme_bw() +
  facet_grid(rows = vars(Gender)) +
  theme(legend.position="none")

print(plot1)

plot1 |> plotly::ggplotly()


```

## demographics

```{r}

visit1 = 
  gp34 |> 
  arrange(`FXS ID`, `Visit Date`) |> 
  group_by(`FXS ID`) |> 
  slice_head(n = 1) |>
  ungroup() |> 
  rename(
    `Age at first visit` = `Age at visit`,
    `Recruited in study phase` = Study
  ) |> 
  left_join(
    gp34 |> count(`FXS ID`, name = "# visits"),
    by = "FXS ID"
  ) |> 
  mutate(`# visits` = factor(`# visits`, levels = 1:6))


```

## Missing visit date

```{r}

gp34 |> filter(is.na(`Visit Date`)) |> 
  select(Study:`Visit Date`)

```

## Duplicate visit date

```{r}

gp34 |> 
  group_by(`FXS ID`, `Visit Date`) |> 
  filter(n() > 1) |> 
  select(Study:`Visit Date`) |> print(n = Inf)

```


## Table 1

### Demographics
```{r}

vars = c(
  "Age at first visit",
  "# visits",
  # "Recruited in study phase",
  "Gender",
  "Primary Ethnicity",
  "Primary Race"
  
)

library(table1)
NA.label = "Missing (blank)"
table1(
  NA.label = NA.label,
  formula(paste("~", paste(formulaic::add.backtick(vars), collapse = " + "), "| `Recruited in study phase`")),
  data = visit1)
```

### APOE

```{r}

table1(
  NA.label = NA.label,
  formula(paste("~", paste(formulaic::add.backtick("ApoE"), collapse = " + "), "| `Recruited in study phase`")),
  data = visit1)
```

### CGG


```{r}

vars = grep("^CGG", names(gp34), value = TRUE)

library(table1)
table1(
  NA.label = NA.label,
  formula(paste("~", paste(formulaic::add.backtick(vars), collapse = " + "), "| `Recruited in study phase`")),
  data = visit1)
```

### everything else

```{r}

vars = c(
  "Drug use",
  "Marijuana use",
  "Alcohol use",
  "# of drinks per day now",
  "# of drinks per day now: missingness",
  "Thyroid Cancer",
  "Skin Cancer",
  "Melanoma",
  "Prostate Cancer",
  "Other Cancer",
  # "Other Cancer (detailed)", # don't include in table
  # "Surgery",
  # "Surgery type",
  # "Surgery: Type/Age",
  # "Surgery 2: Type/Age",
  # "Surgery 3: Type/Age",
  # "Surgery 4: Type/Age",
  # "Surgery 5: Type/Age",
  
  "Intention tremor",
  "Resting tremor",
  "Postural tremor",
  "Intermittent Tremor",
  "Tremor: Age of onset",
  "Tremor: Age of onset: missingness",
  
  "Head tremor",
  "Head Tremor: Age of onset",
  "Head Tremor: Age of onset: missingness",
  
  "Ataxia",
  "Ataxia: severity",
  "Ataxia: Age of onset",
  "Ataxia: Age of onset: missingness",
  
  grep("Parkinson", value = TRUE, names(gp34)),
  
  "FXTAS Stage (0-5)",
  
  grep("BDS-2 Total Score", value = TRUE, names(gp34), fixed = TRUE),
  grep("MMSE Total Score", value = TRUE, names(gp34), fixed = TRUE),
  
  grep("Interviewers Diagnosis", value = TRUE, names(gp34), fixed = TRUE) |> sort(),
  # grep("score", value = TRUE, names(gp34), ignore.case = TRUE) |> sort(),
  
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Somatization (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Obsessive-Compulsive (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Interpersonal Sensitivity T-score: Nonpatient"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Depression (T-score: Nonpatient)"), 
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Anxiety (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Hostility (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Phobia (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Paranoid Ideation (T-score: Nonpatient)",),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Psychoticism (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Global Severity Index (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Positive Symptom Distress Index (T-score: Nonpatient)"),
  grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "Positive Symptom Total (T-score: Nonpatient)"),
  
  "Cerebral Atrophy",
  "Cerebellar Atrophy",
  "Cerebral WM Hyperintensity",
  "Cerebellar WM Hyperintensity",
  "MCP-WM Hyperintensity",
  "Pons-WM Hyperintensity",
  "Sub-Insular WM Hyperintensity",
  "Periventricular WM Hyperintensity",
  "Splenium (CC)-WM Hyperintensity",
  "Genu (CC)-WM Hyperintensity",
  "Corpus Callosum-Thickness",
  
  "Verbal: IQ Score",
  "Verbal Comprehension: Composite Score (VCI)",
  
  "Perceptual Reasoning: Composite Score (PRI)",
  "Working Memory: Composite Score (WMI)", 
  "Processing Speed: Composite Score (PSI)",
  
  "Full Scale: Composite Score FSIQ)", 
  "Full Scale: IQ Score",
  
  "Drugs used",
  
  "SWM Between errors",
  "SST Median correct RT on GO trials",
  "RVP A",
  "OTS Problems solved on first choice",
  "PAL Total errors (adjusted)",
  "RTI Five-choice movement time",
  
  "Lupus",
  "Rheumatoid arthritis",
  "Multiple Sclerosis: Workup",
  "ANA positive",
  "Sjogrens Syndrome",
  "Raynauds Syndrome",
  "Pulmonary Fibrosis"
  # "Immunological Notes"
  
  
  
  
)

library(table1)
table1(
  NA.label = NA.label,
  formula(paste("~", paste(formulaic::add.backtick(vars), collapse = " + "), "| `Recruited in study phase`")),
  data = visit1)
```


### Surgery

```{r}

vars = c(
  
  grep(pattern = "surgery", ignore.case = TRUE, x = names(gp34), value = TRUE)
  
)

library(table1)
table1(
  NA.label = NA.label,
  formula(paste("~", paste(formulaic::add.backtick(vars), collapse = " + "), "| `Recruited in study phase`")),
  data = visit1)
```

