---
title: "Questions about FXTAS Sequence Data"
format:
  html:
    toc: true
    toc-depth: 4
    toc-float: true
    number-sections: true
    embed-resources: true
  docx:
    number-sections: true
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 4
)

# update 'asis' chunk to allow inline code
knitr::knit_engines$set(asis = function(options) {
  if (options$echo && options$eval) knitr::knit_child(text = options$code)
})
```

```{r setup}
#| message: false
library(fxtas)
devtools::load_all()
library(pander)
library(table1)
library(dplyr)
library(magrittr)
NA.label1 = "Missing"
column_var = "Recruited in study phase"
column_var = "FX**"
# load_all()

phase <- ifelse(column_var == "Recruited in study phase", TRUE, FALSE)
cgg <- ifelse(column_var == "FX**", TRUE, FALSE)
```

# General data processing notes

## Missing codes

The missing codes 777, 888, and 999 were converted to `NA` for all variables, unless noted otherwise below.

# Data from first visits

## SCL90

List of patients with missing SCL90:  

:::{.callout-note}
<b>The list can be downloaded to `csv` or `excel` by clicking on the `Download` button at the top of the table.</b>
:::

```{r}
vars = grep(value = TRUE, fixed = TRUE, names(gp34), pattern = "SCL90") |> sort()
# want to exclude categorized and reason missing variables that we created
excl_strings <- c("missingness", "\\*")
na_vars <- vars[grep(paste(excl_strings, collapse = "|"), vars, invert= TRUE)]

scl90_na <- visit1 |>
  # select obs with any missing SCL90 variable
  filter(
    if_any(
      .cols = all_of(na_vars),
      .fns = ~ is.na(.)
    )
  ) |>
  dplyr::select(
    `FXS ID`, `Event Name`, all_of(na_vars)
  )

# create smaller dataset with just SCL90 overall variable
scl90_na_print <- scl90_na |>
  # create single indicator variable
  mutate(
    SCL90 = ifelse(
      if_any(
        .cols = all_of(na_vars),
      .fns = ~ is.na(.)
      ),
      NA,
      "Not Missing"
    )
  ) |>
  dplyr::select(`FXS ID`, `Event Name`, SCL90)
```

```{r}
display_DT(scl90_na, "GP3_GP4_SCL90", group = FALSE)
```
