---
title: "Questions about FXTAS Sequence Data"
format:
  html:
    toc: true
    toc-depth: 4
    toc-float: true
    number-sections: true
    embed-resources: true
  docx:
    number-sections: true
---

```{r, include = FALSE}

knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 4
)

# update 'asis' chunk to allow inline code
knitr::knit_engines$set(asis = function(options) {
  if (options$echo && options$eval) knitr::knit_child(text = options$code)
})
```

```{r setup}
#| message: false
library(fxtas)
devtools::load_all()
library(pander)
library(table1)
library(dplyr)
library(magrittr)
NA.label1 = "Missing"
column_var = "Recruited in study phase"
column_var = "FX**"
# load_all()

phase <- ifelse(column_var == "Recruited in study phase", TRUE, FALSE)
cgg <- ifelse(column_var == "FX**", TRUE, FALSE)
```

# General data processing notes

## Missing codes

The missing codes 777, 888, and 999 were converted to `NA` for all variables, unless noted otherwise below.

# Data from first visits

```{asis, echo=phase}
Here, we review the data from the first visits by each participant, stratified by 
the first study phase in which the participant enrolled (GP3 vs GP4).
```

```{asis, echo=cgg}
Here, we review the data from the first visits by each participant, stratified by CGG (`r paste0("<55 or", " \u2265", "55")`).
```


## BDS2

For `BDS2 Total Score`, codes `777`, `888`, and `999` are treated as NAs.

```{r}

vars = grep("BDS-2 Total Score", value = TRUE, names(gp34), fixed = TRUE)

table1(
  NA.label = NA.label1,
  stratified_formula(vars, column_var),
  # render.continuous = c(.="N", .="Mean (SD)", .="Median [Min,  Max]"),
  data = visit1)

```

<br>

The following patients have missing BDS-2 data. Is it possible some of these patients have BDS-2 data stored outsite of REDCap?

```{r}
bds2_na <- visit1 |>
  filter(is.na(`BDS-2 Total Score`)) |>
  dplyr::select(`FXS ID`, `Event Name`, `BDS-2 Total Score`)
```

```{r}
display_DT(bds2_na, "GP3_GP4_BDS-2", group = FALSE)
```
