---
title: "FXTAS sequence analysis"
format: 
  html: 
    author: 
      - name: Ezra Morrison
        email: demorrison@ucdavis.edu
      - Matt Ponzini
      - Kyoungmi Kim
    toc: false
    theme:
       light: 
         - cosmo
         - custom.scss
       dark: 
         - darkly
         - custom.scss
    cap-location: top
    embed-resources: true
    css: custom.scss
    number-sections: true
    number-depth: 3
    html-math-method: mathjax
    fig-cap-location: top
    code-fold: true
    echo: false
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    bibliography: references.bib

project:
  execute-dir: project
---

Here, we apply the Ordinal **Su**btype and **St**age **In**ference ("SuStaIn") algorithm [@young2021ordinal] to find event sequences for FXTAS patients.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  # fig.width = 7, 
  # fig.height = 10,
  include = TRUE
)
```

```{r setup}
#| message: false
devtools::load_all()
library(tidyverse)
library(reticulate)
```

```{r}
# reticulate::use_condaenv(condaenv = "fxtas")
```

```{r}
#| label: "set run parameters"
N_startpoints = 10L
N_S_max = 4L
N_iterations_MCMC = 1e5L
dataset_name = 'sample_data'
root_dir = here::here()
setwd(root_dir)
output_folder = 
  "output/output.longest" |> 
  fs::dir_create()

synchronize_y_axes = FALSE
```

```{r}

biomarker_groups = compile_biomarker_groups_table()

SuStaInLabels = 
  biomarker_varnames = 
  biomarker_groups |> 
  pull("biomarker")

df = 
  visit1 |> 
  filter(
    !is.na(`FX*`))

biomarker_levels = 
  lapply(df[,biomarker_varnames], F = levels)

df = df |>
  mutate(
    across(
      all_of(biomarker_varnames), 
      ~ as.numeric(.x) - 1)
  )

biomarker_events_table =
  construct_biomarker_events_table(
    biomarker_levels,
    biomarker_groups)

biomarker_plot_order =
  biomarker_events_table |>  pull(biomarker_level)

nlevs = 
  sapply(biomarker_levels, length)


```

```{r}

ModelScores = DataScores = 
  df |> 
  select(all_of(biomarker_varnames)) |> 
  # lapply(F = levels)
  compute_score_levels()


control_data = 
  df |> 
  filter(`FX*` == "CGG < 55")

patient_data = 
  df |> 
  # na.omit() |>
  filter(`FX*` == "CGG >= 55")

prob_correct = 
  control_data |> 
  compute_prob_correct(
    max_prob = .95,
    biomarkers = biomarker_varnames,
    DataScores = DataScores)

prob_dist = compute_prob_dist(
  ModelScores,
  DataScores,
  biomarker_varnames,
  prob_correct
)

prob_nl_dist = prob_dist[1, , ]
prob_score_dist = prob_dist[-1, , ]

```

```{r}

prob_score0 = compute_prob_scores(
    dataset = patient_data,
    biomarker_varnames,
    ModelScores,
    DataScores,
    prob_dist
  )
 
prob_nl = prob_score0[,,1]
prob_score = prob_score0[,,-1, drop = FALSE]

```

```{r "score_vals"}

# sapply(X = biomarker_varnames, F = function(x) 1:nlevs[x])

score_vals = matrix(
  ModelScores[-1] |> as.numeric(),
  byrow = TRUE,
  nrow = length(biomarker_varnames),
  ncol = length(ModelScores) - 1,
  dimnames = list(biomarker_varnames, ModelScores[-1]))

for (i in biomarker_varnames)
{
  score_vals[i,score_vals[i,] > nlevs[i]-1] = 0
}

```

# positional variance diagrams (PVDs) by number of subgroups

## one subgroup

```{r}
#| label: "positional variance diagrams - 1 group"
#| column: page
#| fig-height: !expr pvd_height
#| fig-align: center
#| fig-cap: "positional variance diagrams: 1 subgroup"
#| fig-cap-location: top

results = extract_results_from_pickle(
  n_s = 1,
  dataset_name = dataset_name,
  output_folder = output_folder,
  biomarker_groups = biomarker_groups,
  biomarker_levels = biomarker_levels)

# figs = results |> plot_positional_var()

```

## two subgroups

```{r}
#| label: "positional variance diagrams - 2 groups"
#| layout-ncol: 2
#| fig-height: !expr pvd_height
#| fig-cap: "positional variance diagrams: 2 subgroups"
#| fig-cap-location: top
#| fig-align: center
#| column: page
#| fig-subcap: 
#|   - "Group 1"
#|   - "Group 2"
biomarker_plot_order2 = NULL

results = extract_results_from_pickle(
  n_s = 2,
  dataset_name = dataset_name,
  output_folder = output_folder,
  biomarker_groups = biomarker_groups,
  biomarker_levels = biomarker_levels)

table_subtype_by_demographics(
    patient_data,
    subtype_and_stage_table = results$subtype_and_stage_table
    )

figs = extract_figs_from_pickle(
  synchronize_y_axes = synchronize_y_axes,
  n_s = 2,
  dataset_name = dataset_name,
  output_folder = output_folder,
  score_vals = score_vals,
  biomarker_plot_order = biomarker_plot_order2,
  biomarker_groups = biomarker_groups,
  biomarker_levels = biomarker_levels)
figs |> 
  print_PVDs()

```

## three subgroups

```{r}
figs = extract_figs_from_pickle(
  synchronize_y_axes = synchronize_y_axes,
  n_s = 3,
  dataset_name = dataset_name,
  output_folder = output_folder,
  score_vals = score_vals,
  biomarker_plot_order = biomarker_plot_order2,
  biomarker_groups = biomarker_groups,
  biomarker_levels = biomarker_levels)
```

```{r}
#| label: "positional variance diagrams - 3 groups"
#| layout-ncol: 3
#| fig-height: !expr pvd_height
#| fig-align: center
#| fig-cap: "positional variance diagrams: 3 subgroups"
#| fig-cap-location: top
#| column: page
#| fig-subcap:
#|   - "Group 1"
#|   - "Group 2"
#|   - "Group 3"
library(ggplot2)

figs |> 
  print_PVDs()

```

## References{.unnumbered}

::: {#refs}
:::
