---
title: "SuStaIn-ModelFitting"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{SuStaIn-ModelFitting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  comment = "#>"
)
```

```{r setup}
library(fxtas)
library(tidyverse)
library(reticulate)
```


# Import data

```{r}

df = system.file("extdata", "synthetic_data.xlsx", package = "fxtas") |> readxl::read_excel()

SuStaInLabels = biomarkers = c('Biomarker 1', 'Biomarker 2', 'Biomarker 3',
               'Biomarker 4', 'Biomarker 5')

```

# Set up data for new version of SuStaIn
The objective here is two create to variables:

* `p_NL` -- a subject x region matrix indicating the p that a region is normal for a subject.
* `p_score` -- a subject x (region * score) matrix indicating p that a region is a given score.

Ps should be non-zero. 

```{r}

ModelScores = DataScores = as.character(0:3)

control_data = df |> filter(Category == "Control") |> select(all_of(biomarkers))
patient_data = df |> filter(Category == "Patient") |> select(all_of(biomarkers))

# prob_correct = (control_data == 0) |> colMeans()
prob_correct = 
  df |> 
  filter(Category == "Control") |> 
  summarize(
    across(
      .cols = all_of(biomarkers), 
      .fn = ~ mean(.x == 0))
  ) |> 
  unlist()

prob_dist_dims = 
  list(
    modelscore = ModelScores,
    datascore = DataScores,
    biomarker = biomarkers)

prob_dist = array(
  NA,
  dim = sapply(length, X = prob_dist_dims),
  dimnames = prob_dist_dims)

for (biomarker in biomarkers)
{
  for (datascore in DataScores)
  {
    for (modelscore in ModelScores)
    {
      if(datascore == modelscore)
      {
        prob_dist[modelscore, datascore, biomarker] = prob_correct[biomarker] 
      } else
      {
        prob_dist[modelscore, datascore, biomarker] = 
          (1 - prob_correct[biomarker] ) / (length(DataScores) - 1)
      }
    }
  }
}

prob_nl_dist = prob_dist[1, , ]
prob_score_dist = prob_dist[-1, , ]

```

```{r}

prob_score_dims = 
  list(
  ID = df |> filter(Category == "Patient") |> pull(Index),
  Biomarker = biomarkers,
  model = ModelScores
)
  
prob_score0 = array(
  NA,
  dim = prob_score_dims |> sapply(length),
  dimnames = prob_score_dims
)

for (biomarker in biomarkers)
{
  for (datascore in DataScores)
  {
    for (modelscore in ModelScores)
    {
      prob_score0[patient_data[[biomarker]] == datascore, biomarker, modelscore] = 
        prob_dist[modelscore, datascore, biomarker]
    }
    
  }
}

prob_nl = prob_score0[,,"0"]
prob_score = prob_score0[,,-1]

```

```{r "score_vals"}

score_vals = matrix(
  ModelScores[-1] |> as.numeric(),
  byrow = TRUE,
  nrow = length(biomarkers),
  ncol = length(ModelScores) - 1)



```

# Run SuStaIn model

```{r "set run parameters"}

N_startpoints = 10L
N_S_max = 3L
N_iterations_MCMC = 1e5L
dataset_name = 'sample_data'
output_folder = "output" |> fs::dir_create()
print(output_folder)
```

```{python "initialize-model"}

import pandas
import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import scipy
from glob import glob
import pySuStaIn
import os

os.getcwd()

sustain_input = pySuStaIn.OrdinalSustain(
    r.prob_nl,
    r.prob_score,
    r.score_vals,
    r.SuStaInLabels,
    r.N_startpoints,
    r.N_S_max, 
    r.N_iterations_MCMC, 
    r.output_folder, 
    r.dataset_name, 
    False,
    1)

```

```{python "fit-model", fig.width = 8, fig.height = 9}

[samples_sequence, samples_f, 
ml_subtype, prob_ml_subtype, ml_stage, 
prob_ml_stage, prob_subtype_stage, 
samples_likelihood] = sustain_input.run_sustain_algorithm(plot=True)

```

```{python, include = TRUE, fig.width = 8, fig.height = 9}
plt.show()

```

```{python}

# plot_positional_var()

```


```{r}

# py$samples_sequence

```

