---
title: "test-graphs"
---

```{r}
#| label: setup
library(fxtas)
pvd_height = 8
size.y = 11
output_folder = 
  "output/output.fixed_CV/" |> 
  fs::dir_create()
fig_females_first = extract_figs_from_pickle(
  n_s = 1,
  size.y = size.y,
  rda_filename = "data.RData",
  dataset_name = "females",
  output_folder = "output/output.fixed_CV")

fig_males_first = extract_figs_from_pickle(
  n_s = 1,
  size.y = size.y,
  rda_filename = "data.RData",
  dataset_name = "males",
  output_folder = "output/output.fixed_CV")
```

test
{{< pagebreak >}}
::: landscape

```{r}
#| label: "fig-first-only"
#| fig-height: !expr pvd_height
#| fig-cap: "Estimated event sequence models, stratified by sex, first visits only"
#| layout-ncol: 2
#| fig-subcap:
#|   - "Males"
#|   - "Females"
fig_males_first |> print()
fig_females_first |> print()

```

{{< pagebreak >}}

```{r}
#| label: "fig-justone"
#| fig-height: !expr pvd_height
#| fig-cap: "just one"
fig_females_first |> print()
```

{{< pagebreak >}}


```{r}
#| label: "fig-v2"
#| fig-height: !expr pvd_height
#| fig-cap: "Estimated event sequence models, stratified by sex, first visits only"
#| layout-ncol: 2
#| fig-subcap:
#|   - "Males"
#|   - "Females"
fig_males_first |> print()
fig_females_first |> print()

```


:::

back

test 

{{< pagebreak >}}

tests
