---
title: "Event sequences in Fragile X-associated tremor/ataxia syndrome"
format: 
  html: 
    author: 
      - name: Ezra Morrison
        email: demorrison@ucdavis.edu
      - Matt Ponzini
      - Kyoungmi Kim
      - (more to be added)
    toc: true
    embed-resources: true
    mainfont: serif
    theme:
       light: 
         - cosmo
         - custom.scss
       dark: 
         - darkly
         - custom.scss
    cap-location: top
    css: custom.scss
    number-sections: true
    number-depth: 3
    html-math-method: mathjax
    fig-cap-location: top
    code-fold: true
    echo: false
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    bibliography: references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:  
      dev: svg

project:
  execute-dir: project
---

```{=html}
<style>
.quarto-figure-center > figure {
text-align: center;
}
</style>
```

Here, we are comparing trax+gp34 vs gp34 only, for males:

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  # fig.width = 7, 
  # fig.height = 10,
  include = TRUE
)
```

```{r setup}
#| message: false
devtools::load_all()
library(tidyverse)
library(reticulate)
library(pander)
```

```{r}
# reticulate::use_condaenv(condaenv = "fxtas")
```

```{r}
#| label: "set run parameters"
#| 
fit_models = TRUE
# fit_models = FALSE
run_CV =  TRUE
# run_CV = FALSE

N_startpoints = 10L
N_S_max = 1L
N_S_max_stratified = 1L
N_CV_folds = 0L
N_iterations_MCMC = 1e5L
dataset_name = 'sample_data'
root_dir = here::here()
setwd(root_dir)
output_folder = 
  "output/output.longest" |> 
  fs::dir_create()
```

```{r}

biomarker_groups = compile_biomarker_groups_table()

SuStaInLabels = 
  biomarker_varnames = 
  biomarker_groups |> 
  pull("biomarker")


df = 
  visit1 |> 
  filter(
    !is.na(`FX*`))

biomarker_levels = 
  lapply(df[,biomarker_varnames], F = levels)

trax_df = 
  males_gp34_trax_v1 |> 
  filter(!is.na(`FX*`))

biomarker_levels_trax = 
  lapply(trax_df[,biomarker_varnames], F = levels)

diffs = list()
for (i in biomarker_varnames)
{
  if(setequal(df[[i]], trax_df[[i]]))
  { 
    diffs[[i]] = "no diffs"
  } else
  {
    diffs[[i]] = list(
      gp34 = setdiff(df[[i]], trax_df[[i]]),
      trax = setdiff(trax_df[[i]], df[[i]]))
  }
}


```

# Results

```{r}
#| label: "fig-pvd1"
#| column: screen
#| fig-height: 15
#| fig-align: center
#| fig-cap: "Estimated event sequence models - males only, gp34 vs gp34+trax"
#| fig-cap-location: top
#| layout-ncol: 2
#| fig-subcap:
#|   - "GP34 males only"
#|   - "Trax+GP34 males" 

score_vals_trax = model_dists(
  df = trax_df,
  biomarker_varnames = biomarker_varnames
)

score_vals_gp34 = model_dists(
  df = df,
  biomarker_varnames = biomarker_varnames
)


fig_male = extract_figs_from_pickle(
  n_s = 1,
  dataset_name = "males",
  output_folder = output_folder,
  score_vals = score_vals_gp34,
  biomarker_groups = biomarker_groups,
  biomarker_levels = biomarker_levels) |> 
  print()

fig_male_trax = extract_figs_from_pickle(
  n_s = 1,
  dataset_name = "sample_data",
  output_folder = "output/trax_gp34_males_v1",
  score_vals = score_vals_trax,
  biomarker_groups = biomarker_groups,
  biomarker_levels = biomarker_levels_trax) |> 
  print()


```
