
::: {#suppfig-pvd_chosen_subtypes_linegraphs}

```{r}
#| label: extract-figs-from-pickle-n-s-selected
figs =
  extract_figs_from_pickle(
    size.y = size.y,
    n_s = n_s_selected,
    dataset_name = dataset_name,
    output_folder = output_folder) |>
  rlang::set_names(paste("Subtype", 1:length(figs)))
```

```{r}
#| label: fig-pvd_chosen_subtypes_linegraphs-1
#| fig-height: !expr pvd_line_height
#| fig-width: !expr pvd_line_width
#| fig-cap:
#|    - "**Subtype 1 compared to Subtype 2**"

figs[c(1, 2)] |> pvd_lineplot(text_size = lineplot_text_size)

```

{{< pagebreak >}}

```{r}
#| label: fig-pvd_chosen_subtypes_linegraphs-2
#| fig-height: !expr pvd_line_height
#| fig-width: !expr pvd_line_width
#| fig-cap:
#|    - "**Subtype 1 compared to Subtype 3**"

figs[c(1, 3)] |> pvd_lineplot(text_size = lineplot_text_size)

```

{{< pagebreak >}}

```{r}
#| label: fig-pvd_chosen_subtypes_linegraphs-3
#| fig-height: !expr pvd_line_height
#| fig-width: !expr pvd_line_width
#| fig-cap:
#|    - "**Subtype 1 compared to Subtype 4**"

figs[c(1, 4)] |> pvd_lineplot(text_size = lineplot_text_size)

```

{{< pagebreak >}}

```{r}
#| label: fig-pvd_chosen_subtypes_linegraphs-4
#| fig-height: !expr pvd_line_height
#| fig-width: !expr pvd_line_width
#| fig-cap:
#|    - "**Subtype 2 compared to Subtype 3**"

figs[c(2, 3)] |> pvd_lineplot(text_size = lineplot_text_size)

```

{{< pagebreak >}}

```{r}
#| label: fig-pvd_chosen_subtypes_linegraphs-5
#| fig-height: !expr pvd_line_height
#| fig-width: !expr pvd_line_width
#| fig-cap:
#|    - "**Subtype 2 compared to Subtype 4**"

figs[c(2, 4)] |> pvd_lineplot(text_size = lineplot_text_size)

```

{{< pagebreak >}}

```{r}
#| label: fig-pvd_chosen_subtypes_linegraphs-6
#| fig-height: !expr pvd_line_height
#| fig-width: !expr pvd_line_width
#| fig-cap:
#|    - "**Subtype 3 compared to Subtype 4**"

figs[c(3, 4)] |> pvd_lineplot(text_size = lineplot_text_size)

```

**Differences in event sequences between pairs of latent subtypes.**
`r compact_fig_cap2`

:::
