
## General data processing notes {.appendix}

### Composite variables {#sec-composites .appendix}

#### `"any autoimmune disorder"` {.appendix}

Due to the rare nature of the individual autoimmune diseases, a composite 
variable (`"any autoimmune disorder"`) was created for analysis. 
`"any autoimmune disorder"` was set to `"Yes"` if a patient had Lupus, Rheumatoid arthritis, 
Multiple Sclerosis, ANA positive, Sjogren's Syndrome, Raynaud's Syndrome, 
or Pulmonary Fibrosis; otherwise, it was set to `"No"`.

#### SCID composite variables

Similarly, we combined individual SCID disorders into composite variables,
taking the highest level ("Absent", "Sub-Threshold", or "Threshold") 
among the constituent individual disorders.
Specifically:

`SCID: Mood Disorders` combines:

- "Bipolar I Disorder (MD01), Lifetime" 
- "Bipolar II Disorder (MD02), Lifetime"
- "Other Bipolar Disorder (MD03), Lifetime" 
- "Major Depressive Disorder (MD04), Lifetime"
- "Dysthymic Disorder (MD05), Lifetime"
- "Depressive Disorder NOS (MD06), Lifetime"
- "Mood Disorder Due to GMC (MD07), Lifetime" 
- "Substance-Induced Mood Dis. (MD08), Lifetime"

`"SCID: Substance Use Disorders"` combines:

- "Alcohol (SUD17), Lifetime" 
- "Sedative-Hypnotic-Anxiolytic (SUD18), Lifetime"
- "Cannabis (SUD19), Lifetime"
- "Stimulants (SUD20), Lifetime"
- "Opiod (SUD21), Lifetime"
- "Cocaine (SUD22), Lifetime"
- "Hallucinogenics/ PCP (SUD23), Lifetime"
- "Poly Drug (SUD24), Lifetime"
- "Other (SUD25), Lifetime"

`SCID: Anxiety Disorders` combines:

- "Panic Disorder (ANX26), Lifetime"
- "Agoraphobia without Panic (ANX27), Lifetime"
- "Social Phobia (ANX28), Lifetime"
- "Specific Phobia (ANX29), Lifetime"
- "Obsessive Compulsive (ANX30), Lifetime"
- "Posttraumatic Stress (ANX31), Lifetime"
- "Generalized Anxiety (ANX32), Current Only"
- "Anxiety Due to GMC (ANX33), Lifetime"
- "Substance-Induced Anxiety (ANX34), Lifetime"
- "Anxiety Disorder NOS (ANX35), Lifetime"

`SCID: Somatization Disorders` combines:

- "Somatization Disorder (SOM36)"
- "Pain Disorder (SOM37)"
- "Undifferentiated Somatoform (SOM38)"
- "Body Dysmorphic (SOM40)"
- "Hypochondriasis (SOM39)"

(`SCID: Psychotic Symptoms` is not a composite variable; instead, it is simply a shortened label for "Primary Psychotic Symptoms (PS01), Lifetime".)

<!-- "any autoimmune disorder" includes: -->
<!--     -   "Lupus", -->
<!--     -   "Rheumatoid arthritis", -->
<!--     -   "Multiple Sclerosis: Workup", -->
<!--     -   "ANA positive", -->
<!--     -   "Sjogrens Syndrome", -->
<!--     -   "Raynauds Syndrome", -->
<!--     -   "Pulmonary Fibrosis" -->

<!-- "Any tremor (excluding head)" includes: -->
<!--     -   "Intention tremor", -->
<!--     -   "Resting tremor", -->
<!--     -   "Postural tremor", -->
<!--     -   "Intermittent tremor" -->

<!-- "Any cancer" includes: -->
<!--     -   "Thyroid Cancer", -->
<!--     -   "Skin Cancer", -->
<!--     -   "Melanoma", -->
<!--     -   "Prostate Cancer", -->
<!--     -   "Other Cancer" -->

### Missing codes {.appendix}

The missing codes 777, 888, and 999 were converted to `NA` for all variables, unless noted otherwise below.

### Age of onset {.appendix}

In the RedCap database, the "age of onset" variables were recorded using a mix of precise ages and decade-long ranges (for example, "`130`" = "teens", "`200`" = "twenties", etc.). For analysis as numeric variables, the decade codes were replaced by their midpoints (for example, "`130`" was replaced with 15, "`200`" with 25, etc.). The exception is code "`555`" = "lifelong", which was replaced by the minimum of 10 years and the smallest observed value for that age-of-onset variable; for example, if the smallest observed value for "age of tremor onset" was 8, then "`555`" would be replaced by 8. If the smallest observed value were 11, then "`555`" would be replaced by 10.
