```{r}
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.width = 7.5,
  fig.height = 4
)

# update 'asis' chunk to allow inline code
knitr::knit_engines$set(asis <- function(options) {
  if (options$echo && options$eval) knitr::knit_child(text = options$code)
})
```

```{r}
#| label: setup-demos-unstratified
#| message: false
library(fxtas)
devtools::load_all()
library(pander)
library(table1)
library(dplyr)
library(tidyr)
```

## List of Studies each patient was involved in (GP3, GP4, TRAX)  

For all male patients, list the studies in which they participated.  

```{r}
# store unique IDs that are present in GP3, GP4, and TRAX
gp3_ids <- gp34[gp34$Study == "GP3" & gp34$Gender== "Male", ]$`FXS ID`
gp4_ids <- gp34[gp34$Study == "GP4" & gp34$Gender== "Male", ]$`FXS ID`
trax_ids <- trax$`FXS ID`

males_gp34_trax_v1 <- 
  males_gp34_trax_v1 |> 
  mutate(
  "GP3" = ifelse(`FXS ID` %in% gp3_ids, "GP3", NA_character_),
  "GP4" = ifelse(`FXS ID` %in% gp4_ids, "GP4", NA_character_),
  "TRAX" = ifelse(`FXS ID` %in% trax_ids, "TRAX", NA_character_)
) |>
  unite(
    col = "Studies", GP3, GP4, TRAX, sep = ", ", remove = FALSE, na.rm = TRUE
  )
```

```{r }
males_gp34_trax_v1 |> 
  dplyr::filter(CGG < 200) |> 
  arrange(GP3, GP4, TRAX) |> 
  mutate(Studies = factor(Studies)) |> 
  table1(na.is.category = FALSE, ~ Studies |`FX*`, data = _)
```
