#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom arsenal tableby
#' @importFrom colorspace qualitative_hcl
#' @importFrom dplyr arrange
#' @importFrom dplyr as_tibble
#' @importFrom dplyr between
#' @importFrom dplyr count
#' @importFrom dplyr filter
#' @importFrom dplyr if_all
#' @importFrom dplyr if_any
#' @importFrom dplyr if_else
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr tibble
#' @importFrom forcats fct_na_level_to_value
#' @importFrom forcats fct_other
#' @importFrom fs path
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_fill_gradient
#' @importFrom ggplot2 scale_x_log10
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggtext element_markdown
#' @importFrom glue glue
#' @importFrom magrittr set_names
#' @importFrom plotly ggplotly
#' @importFrom rcartocolor carto_pal
#' @importFrom readxl read_excel
#' @importFrom reticulate import
#' @importFrom reticulate iterate
#' @importFrom reticulate py_load_object
#' @importFrom splitTools create_folds
#' @importFrom table1 table1
#' @importFrom tibble column_to_rownames
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyselect contains
## usethis namespace: end
NULL
