#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom arsenal tableby
#' @importFrom colorspace qualitative_hcl
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr as_tibble
#' @importFrom dplyr between
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_all
#' @importFrom dplyr if_any
#' @importFrom dplyr if_else
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr na_if
#' @importFrom dplyr pick
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr slice_head
#' @importFrom dplyr summarize
#' @importFrom dplyr tibble
#' @importFrom flextable as_flextable
#' @importFrom forcats fct_na_level_to_value
#' @importFrom forcats fct_other
#' @importFrom fs path
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 guide_colorbar
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_gradient
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_x_log10
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggtext element_markdown
#' @importFrom glue glue
#' @importFrom grDevices colorRampPalette
#' @importFrom grDevices colors
#' @importFrom grDevices rgb
#' @importFrom labelled set_label_attribute
#' @importFrom magrittr set_names
#' @importFrom pander pander
#' @importFrom plotly ggplotly
#' @importFrom rcartocolor carto_pal
#' @importFrom readxl read_excel
#' @importFrom reticulate import
#' @importFrom reticulate iterate
#' @importFrom reticulate py_load_object
#' @importFrom rlang .data
#' @importFrom splitTools create_folds
#' @importFrom stats fisher.test
#' @importFrom stats formula
#' @importFrom stats relevel
#' @importFrom stats setNames
#' @importFrom table1 table1
#' @importFrom tibble column_to_rownames
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyselect contains
#' @importFrom tidyselect ends_with
#' @importFrom tidyselect starts_with
#' @importFrom utils head
#' @importFrom utils stack
#' @importFrom utils tail
## usethis namespace: end
NULL
