# mixture_model_grid <- function(X, y, mixtures,
#                                score_names=NULL, class_names=NULL, hist_align='left',
#                                max_rows = Inf,
#                                max_cols = 3){
#   n_particp <- nrow(X)
#   n_biomarkers <- ncol(X)
#   if (is.null(score_names)){
#     score_names <- paste0("BM", 1:n_biomarkers)
#   }
#   if (is.null(class_names)){
#     class_names <- c("CN", "AD")
#   }
#
#   n_x <- min(max_cols,
#              round(sqrt(n_biomarkers)))
#
#   n_y <- ceiling(n_biomarkers/n_x)
#   hist_c <- colors[1:2]
#   fig <- plt.subplots(n_y, n_x, figsize=c(12, 12))
#   for (i in 1:n_biomarkers){
#     bio_X <- X[, i]
#     bio_y <- y[!is.na(bio_X)]
#     bio_X <- bio_X[!is.na(bio_X)]
#
#     hist_dat <- list(bio_X[bio_y == 0],
#                      bio_X[bio_y == 1])
#     n_unique_values_bio_X <- length(unique(bio_X))
#     magic_number <- 5
#     if (n_unique_values_bio_X < magic_number){
#       bin_edges <- unique(bio_X) - 0.5
#       bin_edges <- c(bin_edges, bin_edges[length(bin_edges)] + 1)
#     } else {
#       bin_edges <- 12
#     }
#     leg1 <- ax.flat[i].hist(hist_dat,
#                             label=class_names,
#                             density=TRUE,
#                             color=hist_c,
#                             alpha=0.7,
#                             stacked=TRUE,
#                             align=hist_align,
#                             bins=bin_edges)
#     linspace <- seq(min(bio_X), max(bio_X), length.out=100)
#     linspace <- matrix(linspace, nrow=length(linspace), ncol=1)
#     if (inherits(mixtures[i], "ParametricMM")){
#       controls_score <- mixtures[i].pdf(mixtures[i].theta,
#                                         linspace)
#       patholog_score <- mixtures[i].pdf(mixtures[i].theta,
#                                         linspace)
#     } else {
#       controls_score <- mixtures[i].pdf(linspace)
#       patholog_score <- mixtures[i].pdf(linspace)
#     }
#     probability <- 1-mixtures[i].probability(linspace)
#     probability <- probability * max(c(patholog_score, controls_score))
#     ax.flat[i].plot(linspace, controls_score,
#                     color=colors[1])
#     ax.flat[]
#     # auto-generated by chatGPT, which froze midway through translation and produced a mix of python and R code
# }
